[package]
name = "spot-init"
version = "0.1.0"
authors = ["Nick Cardin <nick@cardin.email>"]
edition = "2018"

[dependencies]
clap = "2.33"
toml = "*"
serde = "1.0"
serde_derive = "1.0"
signal-hook = "*"
crossbeam-channel = "*"
libc = "*"